### ISSUE TITLE
lower case v causes error in the parser

### ISSUE THREAD

**Issue by timelyportfolio** [knsv/mermaid#108]
It appears `v` anywhere inside the diagram spec will cause the parser to fail.  As an example,
`graph LR; v;` fails while `graph LR; V;` works just fine.

ref https://github.com/rich-iannone/DiagrammeR/issues/47

**Comment by timelyportfolio** [comment]
updated to say any "v" in spec causes an error

**Comment by knsv** [comment]
Fixed the problem, it will be included in the next release. Root cause was that the character v is also used for direction down

**Comment by timelyportfolio** [comment]
I see the fix and the test passes.  However, this `graph LR; v;` still does not work.  Should I expect this or just know that `v` is a reserved character.

**Comment by knsv** [comment]
Missed this one or I would have included this in 0.3.3. 

I have added v as a valid for ids so with the next release this will work. Perhaps we should sum things up and do bigger fix for the characters. Right now its one at a time when they pop up.

**Comment by vijay40** [comment]
The wiki should be updated to reflect that direction of graph can also be specified by >,<,^,v.

**Comment by knsv** [comment]
This si working in the mermaid version 0.4.0. Closing this issue. Reopen if this till is a problem.

**Comment by timelyportfolio** [comment]
Sorry to be a pain, but...

`graph TD; v-->a;`  still does not work
`graph TD; V[v]-->a;` does

**Comment by knsv** [comment]
I agree, will look at it. It is a "keyword" but perhaps the grammar could allow this keyword.
